### ISSUE TITLE
Adding an option to convert to Sentance case, Camel Case, Title case etc

### ISSUE THREAD

**Issue by Farzzn** [ramith-kulal/textutils#6]
Examples of various text cases:

1. *Uppercase:*
   - ORIGINAL: hello world
   - UPPERCASE: HELLO WORLD

2. *Lowercase:*
   - ORIGINAL: Hello World
   - LOWERCASE: hello world

3. *Sentence Case:*
   - ORIGINAL: hello world. how are you?
   - SENTENCE CASE: Hello world. How are you?

4. *Camel Case:*
   - ORIGINAL: hello world
   - CAMEL CASE: helloWorld

5. *Title Case:*
   - ORIGINAL: the quick brown fox
   - TITLE CASE: The Quick Brown Fox

6. *Pascal Case:*
   - ORIGINAL: hello world
   - PASCAL CASE: HelloWorld

7. *Snake Case:*
   - ORIGINAL: hello world
   - SNAKE CASE: hello_world

8. *Kebab Case:*
   - ORIGINAL: hello world
   - KEBAB CASE: hello-world

**Comment by ramith-kulal** [comment]
> Examples of various text cases:
> 
> 1. _Uppercase:_
>    
>    * ORIGINAL: hello world
>    * UPPERCASE: HELLO WORLD
> 2. _Lowercase:_
>    
>    * ORIGINAL: Hello World
>    * LOWERCASE: hello world
> 3. _Sentence Case:_
>    
>    * ORIGINAL: hello world. how are you?
>    * SENTENCE CASE: Hello world. How are you?
> 4. _Camel Case:_
>    
>    * ORIGINAL: hello world
>    * CAMEL CASE: helloWorld
> 5. _Title Case:_
>    
>    * ORIGINAL: the quick brown fox
>    * TITLE CASE: The Quick Brown Fox
> 6. _Pascal Case:_
>    
>    * ORIGINAL: hello world
>    * PASCAL CASE: HelloWorld
> 7. _Snake Case:_
>    
>    * ORIGINAL: hello world
>    * SNAKE CASE: hello_world
> 8. _Kebab Case:_
>    
>    * ORIGINAL: hello world
>    * KEBAB CASE: hello-world

 It'd be great adding those features!  What do you think about using a dropdown for these? Simple and effective!

By the way, are you interested in working on these tasks? Let me know your thoughts.

**Comment by Farzzn** [comment]
Check PR
